// <auto-generated />
namespace VEGAACABLE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RemoveImportingInvoiceFromUsedRawMaterialEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveImportingInvoiceFromUsedRawMaterialEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201909022056038_RemoveImportingInvoiceFromUsedRawMaterialEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
